In [1]:
# Getting the dataset to train the model 
!wget https://raw.githubusercontent.com/Seungoh96/hymn_NLP/main/dataset/hymn_dataset.txt

--2024-05-06 11:21:59--  https://raw.githubusercontent.com/Seungoh96/hymn_NLP/main/dataset/hymn_dataset.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8003::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 548649 (536K) [text/plain]
Saving to: 'hymn_dataset.txt.1'

hymn_dataset.txt.1  100%[===================>] 535.79K  --.-KB/s    in 0.07s   

2024-05-06 11:21:59 (7.78 MB/s) - 'hymn_dataset.txt.1' saved [548649/548649]



In [2]:
# read it in to inspect it 
with open('hymn_dataset.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [3]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  227391


In [5]:
# Look at the first 1000 characters
print(text[:200])

만복의 근원 하나님
온 백성 찬송 드리고
저 천사여 찬송하세
성부 성자 성령 -아멘찬양 성부 성자 성령
성 삼위 일체께
영원무궁하기까지 영광을 돌리세
영광을 돌리세 아멘성부 성자와 성령
찬송과 영광 돌려보내세
태초로 지금까지 또 영원무궁토록
성 삼위께 영광 영광 아멘성부 성자와 성령
영원히 영광 받으옵소서
태초로 지금까지 또 영원무궁토록
성 삼위께 영광 아


### Getting Vocabulary in the dataset

In [6]:
# All the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 (),-./123456:=]gins~ –가각간갇갈감갑값갓갔강갖같갚개거걱건걷걸검겁것게겐겔겟겠겨격견결겸겼경곁계고곡곤곧골곱곳공과관광괴교구국군굳굴굶굽궁권궐궤귀귐귓그극근글금급긋긍기긴길김깃깊까깝깨깰꺼껏께껴꼬꼭꼴꽂꽃꾀꾸꾼꿀꿇꿈꿔끄끊끌끓끗끝끼낀낄낌나낙난날남납낫났낭낮낯낱낳내낸낼냄냇냉냐너넉넌널넓넘넣네녀녁년념녔녕녘노녹논놀농높놓뇌뇨누눈눌눕눠뉘느늑는늘능늦늪니닌닐님다닥닦단닫달닭닮담답닷당닻닿대댈더덕던덤덩덮데덴도독돋돌돔돕동돼됐되된될됨됩두둔둘둠둡둥둬뒀뒤드득든듣들듬듭듯등디딜딪따딴딸땀땅때떠떡떤떨떻떼뗍또뚜뚝뚫뛰뜨뜬뜰뜻띄띠라락란랄람랍랐랑래랫랭랴략량러럭런럼럽렀렁렇레렌렐렘려력련렬렴렵렷렸령례로록론롬롭롱뢰뢸룁료루룩룬룰룻뤄뤘류륜륭르른를름릅릇릎리린릴림립마막만많말맑맘맙맛망맞맡매맥맨맬맹맺머먹먼멀멈멍메멘며면멸명모목몫몬몰몸몹못묘무묵묶문묻물뭇뭉뭐므미민믿밀및밑바박밖반받발밝밟밤방밭배백밸뱃버벅번벌범법벗베벼벽변별병볕보복본볼봄봅봉봐뵈뵐뵙부북분불붉붓붙브비빈빌빎빕빗빚빛빠빨빼뺏뻐뻗뻤뼈뼉뿌뿐쁘쁜쁠쁨삐사삭산살삶삼삽샀상새샘샛생샤서석선설섬섭섰성세센셀셈셔셨소속손솔솜솟송쇠수숙순술숨숭숯숲쉬쉰쉴쉼쉽스슨슬슴습승시식신싣실싫심십싶싸싹싼쌀쌈쌍쌓써썩쏘쏟쓰쓴쓸씀씌씨씩씻씽아악안앉않알앓암압앗았앙앞애앨야약양얕얘어억언얹얻얼얽엄업없엇었엎에엔엘엠여역연열염엽엿였영옅옆예옛오옥온올옮옳옴옵옷옹와완왔왕왜외요욕욥용우욱운울움웁웃웅워원월웠웬위윗유육율으윽은을음응의이익인일읽잃임입잇있잉잊잎자작잔잖잘잠잡장재쟁저적전절젊점접정젖제젠져졌조족존졸좁종좋좌죄죠주죽준줄줍중줘즉즐증지직진질짐집짓징짖짙짜짝짧쩌쩔쪽쫓찌찍찔찢차착찬찮찰참찼창찾채책처척천철첨첩청체쳐쳤초촛총최추축춘출춤충춰췄취측치친칠침칩칭캄캐커컫케켜켰코쾌크큰키킨킬킴타탁탄탈탐탑탕태택터털토통투툼퉁트특튼틀틈티파팎판팔패퍼펴편펼평폐포폭표푸푼풀품풍프픈플픔피핀필핍핏핑하한할함합항해햇했행향허헌험헛헤헬헴혀현혈협형혜혠호혹혼홀홉홍화확환활황횃회획효후훈훌휘휩휼흉흐흑흔흘흙흠흡흥희흰히힌힐힘
895


### Create mapping from characters to integers 
```a={}```
creates a dictionary 

In [7]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("안녕 하세요"))
print(decode(encode("안녕 하세요")))

[557, 165, 1, 834, 493, 621]
안녕 하세요


In [8]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch 
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:500])

torch.Size([227391]) torch.int64
tensor([346, 429, 649,   1,  90, 634,   1, 834, 132, 192,   0, 607,   1, 411,
        492,   1, 729, 505,   1, 240, 339,  61,   0, 673,   1, 740, 471, 592,
          1, 729, 505, 834, 493,   0, 492, 439,   1, 492, 663,   1, 492, 310,
          1,   5, 555, 369, 729, 572,   1, 492, 439,   1, 492, 663,   1, 492,
        310,   0, 492,   1, 476, 638,   1, 653, 745, 108,   0, 600, 634, 383,
         81, 834,  96, 102, 706,   1, 600,  71, 646,   1, 220, 339, 493,   0,
        600,  71, 646,   1, 220, 339, 493,   1, 555, 369, 492, 439,   1, 492,
        663, 615,   1, 492, 310,   0, 729, 505,  69,   1, 600,  71,   1, 220,
        302, 428, 145, 493,   0, 790, 748, 312,   1, 706,  92, 102, 706,   1,
        265,   1, 600, 634, 383,  81, 794, 313,   0, 492,   1, 476, 638, 108,
          1, 600,  71,   1, 600,  71,   1, 555, 369, 492, 439,   1, 492, 663,
        615,   1, 492, 310,   0, 600, 634, 891,   1, 600,  71,   1, 403, 643,
        612, 499, 485,   0, 790

### Splitting train and val dataset

In [9]:
# Let's now split up the data into train and validation sets 
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [10]:
block_size = 8 
train_data[:block_size+1]

tensor([346, 429, 649,   1,  90, 634,   1, 834, 132])

In [11]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([346]) the target: 429
when input is tensor([346, 429]) the target: 649
when input is tensor([346, 429, 649]) the target: 1
when input is tensor([346, 429, 649,   1]) the target: 90
when input is tensor([346, 429, 649,   1,  90]) the target: 634
when input is tensor([346, 429, 649,   1,  90, 634]) the target: 1
when input is tensor([346, 429, 649,   1,  90, 634,   1]) the target: 834
when input is tensor([346, 429, 649,   1,  90, 634,   1, 834]) the target: 132


In [12]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[399, 280,   1, 439, 251, 764,   1, 257],
        [834, 370,   1, 859, 473, 132,   1, 729],
        [834,  51, 159,   0, 132,   1, 500, 694],
        [226, 528,   1, 696,   1, 132,   1, 729]])
targets:
torch.Size([4, 8])
tensor([[280,   1, 439, 251, 764,   1, 257,   0],
        [370,   1, 859, 473, 132,   1, 729, 505],
        [ 51, 159,   0, 132,   1, 500, 694,   1],
        [528,   1, 696,   1, 132,   1, 729, 572]])
----
when input is [399] the target: 280
when input is [399, 280] the target: 1
when input is [399, 280, 1] the target: 439
when input is [399, 280, 1, 439] the target: 251
when input is [399, 280, 1, 439, 251] the target: 764
when input is [399, 280, 1, 439, 251, 764] the target: 1
when input is [399, 280, 1, 439, 251, 764, 1] the target: 257
when input is [399, 280, 1, 439, 251, 764, 1, 257] the target: 0
when input is [834] the target: 370
when input is [834, 370] the target: 1
when input is [834, 370, 1] the target: 859
when input is

## Bigram Model
### Breakdown 
You first have to embed each token in your input. This means that you are embedding each token with a vector of dimension that matches your vocab size. 
You do that through ```nn.Embedding()```; with ```nn.Embedding```, you create a matrix that is of size (vocab x vocab). \\
Now, after 

In [25]:
import torch
import torch.nn as nn 
from torch.nn import functional as F 
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):
    
    def __init__(self,vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table 
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
    
    def forward(self, idx, targets=None):
        # idx and targets are both (B,T) tensor of integers 
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None: 
            loss = None
        else: 
            B,T,C = logits.shape
            logits = logits.view(B*T,C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B,T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step 
            logits = logits[:, -1, :] # becomes (B,C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B,C)
            # sample from the distribution
            
            idx_next = torch.multinomial(probs, num_samples=1) # (B,1)
            # append sampled index to the running sequence 
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1,1), dtype=torch.long), max_new_tokens=1)[0].tolist()))

tensor(0.8842, grad_fn=<SelectBackward0>)
tensor(280)
torch.Size([32, 895])
tensor(7.1132, grad_fn=<NllLossBackward0>)

흠


In [ ]:
# Create a PyTorch Optimizer
optimizer = torch.optim.AdamW(m.parameters(),lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(100): 
    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb,yb)
    optimizer.zeros_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.items())